name = "azan-noor"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]

# Cloudflare Pages deployment
pages_build_output_dir = ".vercel/output/static"

[[d1_databases]]
binding = "DB"
database_name = "azan-noor-db"
database_id = "6550becf-65db-485c-9512-5049f695f40f"

[vars]
NEXT_PUBLIC_APP_URL = "https://azan-noor.pages.dev"
